### PR TITLE
use prop-types module instead of deprecated React.PropTypes

### PR DESCRIPTION
**Pull request by dbuezas**

### CODE REVIEW

**Comment by leonardowf** [comment]
Thanks. I will merge asap

**Comment by dbuezas** [comment]
Great! :)

I added `"prop-types": "^15.6.0"` as dependency in package.json and `'prop-types'` in gulpfile.js, everything seems to work (published under our npm scope and it works) but I am not familiar with `react-component-gulp-tasks` so you may want to double check that first.

**Comment by Hagbarth** [comment]
Is there an update here?

**Comment by dbuezas** [comment]
been using my branch in production for 2 weeks without issues

**Comment by leonardowf** [comment]
Merged and released under 1.0.16, thanks 👍

**Pull request merged**
